---
title: "COVID Vietnam"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(gt)
library(gtsummary)
library(ggplot2)
library(targets)
library(data.table)
library(readxl)
```

```{r}
data_path <- file.path(Lmisc::get.dropbox.folder(), "Workspace", "Database", "COVID19")
```

```{r}
today <- Sys.Date()
```

## cases

Source:

* HCDC bao cao truc
* HCDC CDS: tong
* HCDC CDS: chitiet
* HCDC CDS: test nhanh
* NCSC

### HCDC CDS

```{r}
summary_xn_file <- function(path) {
  require(dplyr)
  tmp_files <- list.files(path = path, pattern = ".xlsx", full.names = TRUE)
  output <- data.frame(path = tmp_files) %>%
    mutate(name = gsub(pattern = ".xlsx", replacement = "", x = basename(tmp_files)),
           source = case_when(
             grepl(pattern = "tong", x = name) == TRUE ~ "tong",
             grepl(pattern = "chitiet", x = name) == TRUE ~ "chitiet",
             grepl(pattern = "testnhanh", x = name) == TRUE ~ "testnhanh"
           ),
           type = case_when(
             grepl(pattern = "don", x = name) == TRUE ~ "invidivual",
             grepl(pattern = "gop", x = name) == TRUE ~ "pooled",
             TRUE ~ "all"
           ),
           result = case_when(
             grepl(pattern = "chua", x = name) == TRUE ~ "not available",
             grepl(pattern = "duong", x = name) == TRUE ~ "positive",
             grepl(pattern = "am", x = name) == TRUE ~ "negative",
             grepl(pattern = "khac", x = name) == TRUE ~ "other",
             TRUE ~ "all"
           ),
           date = sapply(name, function(x){strsplit(x, split = "_")[[1]][2]}),
           year = substr(x = date, start = 1, stop = 4),
           month = substr(x = date, start = 5, stop = 6),
           day_start = substr(x = date, start = 7, stop = 8),
           day_stop  = substr(x = date, start = 10, stop = 11),
           date_start = ymd(ifelse(day_start != "00", paste(year, month, day_start), 
                                   ifelse(year == "2020", "2020 01 01", NA))),
           date_stop = ymd(ifelse(day_stop != "", paste(year, month, day_stop), 
                                  ifelse(year == "2020", "2020 12 31", 
                                         ifelse(month != "00", paste(year, month, day_start), NA)))),
           date_modified = ymd_hms(sapply(tmp_files, function(x) as.character(file.info(x)$mtime)))
           )
  return(output)
}

get_xn_file_latest <- function(path = file.path("data", "HCDC", "database", "testing", "tatca"), type = c("tong", "chitiet")) {
  if (length(type) == 2) {stop("Please select type of lab data")}
  require(dplyr)
  tmp_files <- list.files(path = path, pattern = paste0(type, "_"), full.names = TRUE)
  tmp_files2 <- basename(tmp_files)
  return(data.frame(
    file_name = tmp_files,
    real_name = sapply(tmp_files2, function(x) {
      return(paste(strsplit(gsub(pattern = ".xlsx", replacement = "", x = x), split = "_")[[1]][1:2], collapse = "_"))
    }),
    mtime = sapply(tmp_files, function(x) file.info(x)$mtime)
  ) %>%
    group_by(real_name) %>%
    arrange(desc(mtime)) %>%
    slice(1) %>%
    ungroup())
}
```


```{r}
maugop_duong <- c("MAU GOP DUONG TINH", "MAU GOP DUONG TINH (KHAN CAP)")
testnhanh_duong <- c("TEST NHANH DUONG TINH", "TEST NHANH DUONG TINH (KHAN CAP)")
tamsoat_csyt <- c("TAM SOAT KHI CO SO Y TE CO F0", "TAM SOAT KHI CO SO Y TE CO F0 (KHAN CAP)", "TAM SOAT PK/BV", "TAM SOAT TAI BENH VIEN", "TAM SOAT TAI BENH VIEN (KHAN CAP)")
tamsoat_khambenh <- c("TAM SOAT NGUOI DEN KHAM BENH, SU DUNG DICH VU Y TE (KHAN CAP)",
                      "TAM SOAT NGUOI DEN KHAM BENH, SU DUNG DICH VU Y TE",
                      "TAM SOAT NGUOI DEN KHAM BENH", "SANG LOC KHAM BENH",
                      "SANG LOC KHAM BENH (KHAN CAP)", "DOI TUONG CO TRIEU CHUNG TAI CO SO KHAM CHUA BENH")
tamsoat_nguyco_ratcao <- c("TAM SOAT NGUOI NGUY CO RAT CAO (#F1 GAN)", "TAM SOAT NGUOI NGUY CO RAT CAO (#F1 GAN) (KHAN CAP)", "TAM SOAT NGUOI NGUY CO RAT CAO (#F1)", "NGHI NGO NHIEM COVID-19")
tamsoat_nguyco_cao <- c("TAM SOAT NGUOI NGUY CO CAO (#F1 XA)", "TAM SOAT NGUOI NGUY CO CAO (#F1 XA) (KHAN CAP)")
tamsoat_nguyco_cao_bv <- c("DOI TUONG NGUY CO CAO TAI CO SO KHAM CHUA BENH" )
tamsoat_nguyco_cao_congdong <- c("DOI TUONG NGUY CO CAO TRONG CONG DONG")
tamsoat_nguyco <- c("TAM SOAT NGUOI CO NGUY CO (#F2)", "TAM SOAT NGUOI CO NGUY CO (#F2, F KHAC)", "TAM SOAT NGUOI CO NGUY CO (#F2, F KHAC) (THUONG QUY)", "TAM SOAT F KHAC")
tamsoat_vhh <- c("TAM SOAT CHUM CA VIEM HO HAP", "TAM SOAT CHUM CA VIEM HO HAP (KHAN CAP)")
dieutra_dich <- c("DIEU TRA DICH", "DOI TUONG DIEU TRA DICH", "DIEU TRA DICH (KHAN CAP)")
kiemdich <- c("KIEM DICH", "DOI TUONG KIEM DICH")
kiemdich_trongnuoc <- c("KIEM DICH NGUOI VE TU VUNG DICH TRONG NUOC", "KIEM DICH NGUOI VE TU VUNG DICH TRONG NUOC (THUONG QUY)")
kiemdich_ngoainuoc <- c("KIEM DICH NGUOI VE TU NUOC NGOAI", "KIEM DICH NGUOI VE TU NUOC NGOAI (THUONG QUY)")
giamsat_congdong <- c("GIAM SAT CONG DONG (THUONG QUY)", "GIAM SAT CONG DONG", "TAM SOAT CONG DONG")
giamsat_trongdiem <- c("GIAM SAT TRONG DIEM")
giamsat_bv <- c("GIAM SAT THUONG QUY TAI BV", "GIAM SAT THUONG QUY", "GIAM SAT THUONG QUY (THUONG QUY)", "GIAM SAT DINH KY")
theo_yeucau <- c("THEO YEU CAU")
xetnghiemlai <- c("XET NGHIEM LAI")
sau_cltt <- c("SAU CACH LY TAP TRUNG")
theodoi_f0 <- c("XET NGHIEM THEO DOI F0")
theodoi_f0_csyt <- c("XET NGHIEM THEO DOI F0 TAI CO SO Y TE", "XET NGHIEM THEO DOI F0 TAI CO SO Y TE (THUONG QUY)")
theodoi_f0_nha <- c("XET NGHIEM THEO DOI F0 TAI NHA", "XET NGHIEM THEO DOI F0 TAI NHA (THUONG QUY)")
theodoi_f0_saudieutri <- c("XET NGHIEM THEO DOI F0 SAU DIEU TRI (THUONG QUY)", "SAU DIEU TRI", "XET NGHIEM THEO DOI F0 SAU DIEU TRI")
theodoi_khac <- c("XET NGHIEM THEO DOI TRUONG HOP KHAC", "XET NGHIEM THEO DOI TRUONG HOP KHAC (THUONG QUY)")
khac <- c("KHAC")
```

```{r}
data_hcdc_path <- file.path(data_path, "HCDC", "testing")

## summarise data file 
sum_current_file <- summary_xn_file(path = data_hcdc_path)
sum_current_file_latest <- sum_current_file %>%
  group_by(date, source, type, result) %>%
  arrange(desc(date_modified)) %>%
  slice(1) %>%
  ungroup()
```

#### XN chi tiết 

```{r}
xn_chitiet_newest <- subset(sum_current_file_latest, source == "chitiet")
xnchitiet <- NULL

for (i in c(1:nrow(xn_chitiet_newest))) {
  cat(i, "/", nrow(xn_chitiet_newest), "\n")
  xni <- janitor::clean_names(data.table(read_excel(path = xn_chitiet_newest$path[i], skip = 0, col_types = "text")))
  xni$file <- xn_chitiet_newest$name[i]
  xnchitiet <- rbind(xnchitiet, xni, fill = TRUE)
}

saveRDS(xnchitiet, file = file.path(data_path, "VAD", "xnchitiet_raw.rds"))
xnchitiet <- readRDS(file.path(data_path, "VAD", "xnchitiet_raw.rds"))

xn_chitiet <- data.table(xnchitiet %>%
                           select(-thoi_gian_co_ket_qua_theo_he_thong, -orf1ab) %>%
                           mutate_all(.funs = toupper) %>%
                           rowwise() %>%
                           mutate(so_nguoi = as.numeric(ifelse(loai_mau_xn == "MẪU ĐƠN", 1, length(strsplit(ho_va_ten, split = ",")[[1]])))) %>%
                           ungroup() %>%
                           mutate(hcm = ifelse(is.na(tinh_thanh), 2,
                                               ifelse(tinh_thanh == "THÀNH PHỐ HỒ CHÍ MINH", 1, 0)),
                                  quanhuyen = case_when(
                                    hcm == 2 ~ "0. KHONG BIET",
                                    hcm == 0 ~ "0. NGOAI TPHCM",
                                    is.na(quan_huyen) ~ "0. KHONG BIET",
                                    quan_huyen %in% c("QUẬN 01", "QUẬN 1") ~ "QUẬN 01",
                                    quan_huyen %in% c("QUẬN 03", "QUẬN 3") ~ "QUẬN 03",
                                    quan_huyen %in% c("QUẬN 04", "QUẬN 4") ~ "QUẬN 04",
                                    quan_huyen %in% c("QUẬN 05", "QUẬN 5") ~ "QUẬN 05",
                                    quan_huyen %in% c("QUẬN 06", "QUẬN 6") ~ "QUẬN 06",
                                    quan_huyen %in% c("QUẬN 07", "QUẬN 7") ~ "QUẬN 07",
                                    quan_huyen %in% c("QUẬN 08", "QUẬN 8") ~ "QUẬN 08",
                                    quan_huyen %in% c("QUẬN 02", "QUẬN 2", "QUẬN 09", "QUẬN 9", "QUẬN THỦ ĐỨC", "THÀNH PHỐ THỦ ĐỨC") ~ "THÀNH PHỐ THỦ ĐỨC",
                                    quan_huyen %in% c("HUYỆN BÌNH CHÁNH", "HUYỆN CẦN GIỜ", "HUYỆN CỦ CHI", "HUYỆN HÓC MÔN", "HUYỆN NHÀ BÈ", "QUẬN BÌNH TÂN", "QUẬN BÌNH THẠNH", "QUẬN GÒ VẤP", "QUẬN PHÚ NHUẬN", "QUẬN TÂN BÌNH", "QUẬN TÂN PHÚ") ~ as.character(quan_huyen),
                                    TRUE ~ "0. KHONG BIET"
                                  ),
                                  
                                  namsinh = ifelse(is.na(nam_sinh), NA,
                                                   ifelse(as.numeric(nam_sinh) <= 1921 | as.numeric(nam_sinh) > 2021, NA, as.numeric(nam_sinh))),
                                  tuoi = 2021 - namsinh,
                                  nhomtuoi = cut(tuoi, breaks = c(seq(0, 85, 5), 150), right = FALSE,
                                                 labels = c("0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85+")),
                                  nhomtuoi2 = ifelse(is.na(nhomtuoi), "MISSING", as.character(nhomtuoi)),
                                  gioi = gioi_tinh,
                                  tuoi_gioi = case_when(
                                    is.na(gioi) | is.na(tuoi) ~ NA_character_,
                                    gioi == "NAM" & tuoi <= 14 ~ "NAM 0-14",
                                    gioi == "NAM" & tuoi > 14 & tuoi <= 24 ~ "NAM 15-24",
                                    gioi == "NAM" & tuoi > 24 & tuoi <= 44 ~ "NAM 25-44",
                                    gioi == "NAM" & tuoi > 44 & tuoi <= 59 ~ "NAM 45-59",
                                    gioi == "NAM" & tuoi > 59 ~ "NAM 60+",
                                    gioi == "NỮ" & tuoi <= 14 ~ "NỮ 0-14",
                                    gioi == "NỮ" & tuoi > 14 & tuoi <= 24 ~ "NỮ 15-24",
                                    gioi == "NỮ" & tuoi > 24 & tuoi <= 44 ~ "NỮ 25-44",
                                    gioi == "NỮ" & tuoi > 44 & tuoi <= 59 ~ "NỮ 45-59",
                                    gioi == "NỮ" & tuoi > 59 ~ "NỮ 60+",
                                    TRUE ~ NA_character_
                                  ),
  
                                  test_datetime_taken = dmy_hm(thoi_gian_lay_mau, tz = "Asia/Ho_Chi_Minh"),
                                  test_date_taken = date(test_datetime_taken),
                                  test_datetime_result = dmy_hm(thoi_gian_tra_ket_qua, tz = "Asia/Ho_Chi_Minh"),
                                  test_date_result = date(test_datetime_result),
                                  test_result = case_when(
                                    is.na(ket_qua) ~ "CHUA XAC DINH",
                                    grepl(pattern = "DƯƠNG", x = ket_qua) ~ "DUONG TINH",
                                    grepl(pattern = "ÂM", x = ket_qua) ~ "AM TINH",
                                    grepl(pattern = "XÁC ĐỊNH", x = ket_qua) ~ "CHUA XAC DINH",
                                    grepl(pattern = "LẤY MẪU LẠI|MẪU KHÔNG ĐẠT|NGHI NGỜ", x = ket_qua) ~ "KHONG DAT",
                                    TRUE ~ "KHAC"
                                  ),
                                  test_reason = toupper(stringi::stri_trans_general(str = ly_do_xn,  id = "Latin-ASCII")),
                                  test_reason2 = case_when(
                                    is.na(test_reason) ~ "MISSING",
                                    test_reason %in% maugop_duong ~ "01. MAU GOP DUONG",
                                    test_reason %in% testnhanh_duong ~ "02. TEST NHANH DUONG",
                                    test_reason %in% tamsoat_csyt ~ "03. TAM SOAT CSYT",
                                    test_reason %in% tamsoat_khambenh ~ "04. TAM SOAT KHAM BENH",
                                    test_reason %in% tamsoat_nguyco_ratcao ~ "05. TAM SOAT NGUY CO RAT CAO",
                                    test_reason %in% c(tamsoat_nguyco_cao, tamsoat_nguyco_cao_bv, tamsoat_nguyco_cao_congdong) ~ "06. TAM SOAT NGUY CO CAO",
                                    test_reason %in% tamsoat_nguyco ~ "07. TAM SOAT NGUY CO",
                                    test_reason %in% tamsoat_vhh ~ "08. TAM SOAT VHH",
                                    test_reason %in% dieutra_dich ~ "09. DIEU TRA DICH",
                                    test_reason %in% c(kiemdich, kiemdich_trongnuoc, kiemdich_ngoainuoc) ~ "10. KIEM DICH",
                                    test_reason %in% c(giamsat_congdong) ~ "11. GIAM SAT CONG DONG",
                                    test_reason %in% c(giamsat_trongdiem) ~ "12. GIAM SAT TRONG DIEM",
                                    test_reason %in% giamsat_bv ~ "13. GIAM SAT BV",
                                    test_reason %in% theo_yeucau ~ "14. THEO YEU CAU",
                                    test_reason %in% xetnghiemlai ~ "15. XET NGHIEM LAI",
                                    test_reason %in% c(sau_cltt, theodoi_f0, theodoi_f0_csyt, theodoi_f0_nha, theodoi_f0_saudieutri, theodoi_khac) ~ "16. THEO DOI",
                                    test_reason %in% khac ~ "17. KHAC",
                                    TRUE ~ as.character(test_reason)
                                  ),
                                  
                                  test_type = case_when(
                                    is.na(ky_thuat_xn) ~ "MISSING",
                                    (ky_thuat_xn %in% c("11-08-2021", "14-08-2021")) | (grepl(pattern = "COUNTIF|PCR|U07T|VLOOKUP", x = ky_thuat_xn)) ~ "PCR",
                                    grepl(pattern = "TEST NHANH", x = ky_thuat_xn) ~ "TEST NHANH",
                                    grepl(pattern = "TEST MD", x = ky_thuat_xn) ~ "TEST MD",
                                    grepl(pattern = "NUÔI CẤY TẾ BÀO|PHÂN LẬP", x = ky_thuat_xn) ~ "PHAN LAP VIRUS",
                                    TRUE ~ "KHONG RO"
                                  ),
                                  
                                  test_place = toupper(stringi::stri_trans_general(str = noi_lay_mau,  id = "Latin-ASCII")),
                                  test_place2 = case_when(
                                    is.na(test_place) ~ NA_character_,
                                    test_place %in% c("PHIEN XET NGHIEM MAU") ~ NA_character_,
                                    grepl(pattern = "NOI DIEU TRI NGUOI BENH COVID|BENH VIEN DIEU TRI COVID|KHU CACH LY DIEU TRI F0", x = test_place) ~ "01. NƠI ĐIỀU TRỊ NGƯỜI BỆNH COVID",
                                    grepl(pattern = "CO SO Y TE KHONG DIEU TRI COVID", x = test_place) ~ "02. CƠ SỞ Y TẾ KHÔNG ĐIỀU TRỊ COVID",
                                    grepl(pattern = "KHU CACH LY", x = test_place) ~ "03. KHU CÁCH LY",
                                    grepl(pattern = "KHU PHONG TOA", x = test_place) ~ "04. KHU PHONG TỎA",
                                    grepl(pattern = "KCN, KCX, KHU CONG NGHE CAO, CSSX/KD|KCN, KCX, KHU CONG NGHE CAO, CSSX/KD|CO SO SAN XUAT", x = test_place) ~ "05. CƠ SỞ SẢN XUẤT",
                                    grepl(pattern = "CO QUAN HANH CHINH, CONG SO|CO QUAN HANH CHINH, CONG SO|TRU SO LAM VIEC", x = test_place) ~ "06. CÔNG SỞ",
                                    grepl(pattern = "CONG DONG", x = test_place) ~ "07. CỘNG ĐỒNG",
                                    grepl(pattern = "DON VI THUONG XUYEN LUU TRU DONG NGUOI|DON VI THUONG XUYEN LUU TRU DONG NGUOI", x = test_place) ~ "08. NƠI LƯU TRÚ ĐÔNG NGƯỜI", 
                                    grepl(pattern = "CHO, SIEU THI, CUA HANG TIEN LOI|CHO, SIEU THI, CUA HANG TIEN LOI", x = test_place) ~ "09. CHỢ, SIÊU THỊ",
                                    grepl(pattern = "SAN BAY, BEN XE, BEN TAU, GA DUONG SAT|SAN BAY, BEN XE, BEN TAU, GA DUONG SAT", x = test_place) ~ "10. SÂN BAY, BẾN XE, GA",
                                    grepl(pattern = "TRUONG HOC", x = test_place) ~ "11. TRƯỜNG HỌC", 
                                    grepl(pattern = "TAI NHA", x = test_place) ~ "12. TẠI NHÀ",
                                    grepl(pattern = "VUNG XANH", x = test_place) ~ "13. VÙNG XANH",
                                    grepl(pattern = "VUNG CAN XANH", x = test_place) ~ "14. VÙNG CẬN XANH",
                                    grepl(pattern = "VUNG VANG", x = test_place) ~ "15. VÙNG VÀNG",
                                    grepl(pattern = "VUNG CAM", x = test_place) ~ "16. VÙNG CAM",
                                    grepl(pattern = "VUNG DO", x = test_place) ~ "17. VÙNG ĐỎ", 
                                    TRUE ~ "18. KHAC"
                                  )
                           ))

saveRDS(xn_chitiet, file = file.path(data_path, "VAD", "xn_chitiet.rds"))

#with(xn_chitiet, table(test_reason, test_place))
```

#### XN tong 

```{r}
## xn_tong
xn_tong_newest <- subset(sum_current_file_latest, source == "tong")
xntong <- NULL

for (i in c(1:nrow(xn_tong_newest))) {
  cat(i, "/", nrow(xn_tong_newest), "\n")
  xni <- janitor::clean_names(data.table(read_excel(path = xn_tong_newest$path[i], skip = 5, col_types = "text")))
  xni$file <- xn_chitiet_newest$name[i]
  xntong <- rbind(xntong, xni, fill = TRUE)
}
saveRDS(xntong, file = file.path(data_path, "VAD", "xntong_raw.rds"))

xntong <- readRDS(file.path(data_path, "VAD", "xntong_raw.rds"))
xn_tong <- data.table(xntong %>%
                           mutate_all(.funs = toupper) %>%
                           rowwise() %>%
                           mutate(so_nguoi = as.numeric(ifelse(loai_mau == "MẪU ĐƠN", 1, length(strsplit(ho_va_ten, split = ",")[[1]])))) %>%
                           ungroup() %>%
                           mutate(hcm = ifelse(is.na(tinh_thanh), 2,
                                               ifelse(tinh_thanh == "THÀNH PHỐ HỒ CHÍ MINH", 1, 0)),
                                  quanhuyen = case_when(
                                    hcm == 2 ~ "0. KHONG BIET",
                                    hcm == 0 ~ "0. NGOAI TPHCM",
                                    is.na(quan_huyen) ~ "0. KHONG BIET",
                                    quan_huyen %in% c("QUẬN 01", "QUẬN 1") ~ "QUẬN 01",
                                    quan_huyen %in% c("QUẬN 03", "QUẬN 3") ~ "QUẬN 03",
                                    quan_huyen %in% c("QUẬN 04", "QUẬN 4") ~ "QUẬN 04",
                                    quan_huyen %in% c("QUẬN 05", "QUẬN 5") ~ "QUẬN 05",
                                    quan_huyen %in% c("QUẬN 06", "QUẬN 6") ~ "QUẬN 06",
                                    quan_huyen %in% c("QUẬN 07", "QUẬN 7") ~ "QUẬN 07",
                                    quan_huyen %in% c("QUẬN 08", "QUẬN 8") ~ "QUẬN 08",
                                    quan_huyen %in% c("QUẬN 02", "QUẬN 2", "QUẬN 09", "QUẬN 9", "QUẬN THỦ ĐỨC", "THÀNH PHỐ THỦ ĐỨC") ~ "THÀNH PHỐ THỦ ĐỨC",
                                    quan_huyen %in% c("HUYỆN BÌNH CHÁNH", "HUYỆN CẦN GIỜ", "HUYỆN CỦ CHI", "HUYỆN HÓC MÔN", "HUYỆN NHÀ BÈ", "QUẬN BÌNH TÂN", "QUẬN BÌNH THẠNH", "QUẬN GÒ VẤP", "QUẬN PHÚ NHUẬN", "QUẬN TÂN BÌNH", "QUẬN TÂN PHÚ") ~ as.character(quan_huyen),
                                    TRUE ~ "0. KHONG BIET"
                                  ),
                                  
                                  namsinh = ifelse(is.na(nam_sinh), NA,
                                                   ifelse(as.numeric(nam_sinh) <= 1921 | as.numeric(nam_sinh) > 2021, NA, as.numeric(nam_sinh))),
                                  tuoi = 2021 - namsinh,
                                  nhomtuoi = cut(tuoi, breaks = c(seq(0, 85, 5), 150), right = FALSE,
                                                 labels = c("0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85+")),
                                  nhomtuoi2 = ifelse(is.na(nhomtuoi), "MISSING", as.character(nhomtuoi)),
                                  gioi = gioi_tinh,
                                  tuoi_gioi = case_when(
                                    is.na(gioi) | is.na(tuoi) ~ NA_character_,
                                    gioi == "NAM" & tuoi <= 14 ~ "NAM 0-14",
                                    gioi == "NAM" & tuoi > 14 & tuoi <= 24 ~ "NAM 15-24",
                                    gioi == "NAM" & tuoi > 24 & tuoi <= 44 ~ "NAM 25-44",
                                    gioi == "NAM" & tuoi > 44 & tuoi <= 59 ~ "NAM 45-59",
                                    gioi == "NAM" & tuoi > 59 ~ "NAM 60+",
                                    gioi == "NỮ" & tuoi <= 14 ~ "NỮ 0-14",
                                    gioi == "NỮ" & tuoi > 14 & tuoi <= 24 ~ "NỮ 15-24",
                                    gioi == "NỮ" & tuoi > 24 & tuoi <= 44 ~ "NỮ 25-44",
                                    gioi == "NỮ" & tuoi > 44 & tuoi <= 59 ~ "NỮ 45-59",
                                    gioi == "NỮ" & tuoi > 59 ~ "NỮ 60+",
                                    TRUE ~ NA_character_
                                  ),
                                  test_datetime_taken = dmy_hm(thoi_gian_lay_mau, tz = "Asia/Ho_Chi_Minh"),
                                  test_date_taken = date(test_datetime_taken),
                                  test_datetime_result = dmy_hm(thoi_gian_ket_qua, tz = "Asia/Ho_Chi_Minh"),
                                  test_date_result = date(test_datetime_result),
                                  test_result = case_when(
                                    is.na(ket_qua) ~ "CHUA XAC DINH",
                                    grepl(pattern = "DƯƠNG", x = ket_qua) ~ "DUONG TINH",
                                    grepl(pattern = "ÂM", x = ket_qua) ~ "AM TINH",
                                    grepl(pattern = "XÁC ĐỊNH", x = ket_qua) ~ "CHUA XAC DINH",
                                    grepl(pattern = "LẤY MẪU LẠI|MẪU KHÔNG ĐẠT|NGHI NGỜ", x = ket_qua) ~ "KHONG DAT",
                                    TRUE ~ "KHAC"
                                  ),
                            
                                  test_reason = toupper(stringi::stri_trans_general(str = ly_do_xn,  id = "Latin-ASCII")),
                                  test_reason2 = case_when(
                                    is.na(test_reason) ~ "MISSING",
                                    test_reason %in% maugop_duong ~ "01. MAU GOP DUONG",
                                    test_reason %in% testnhanh_duong ~ "02. TEST NHANH DUONG",
                                    test_reason %in% tamsoat_csyt ~ "03. TAM SOAT CSYT",
                                    test_reason %in% tamsoat_khambenh ~ "04. TAM SOAT KHAM BENH",
                                    test_reason %in% tamsoat_nguyco_ratcao ~ "05. TAM SOAT NGUY CO RAT CAO",
                                    test_reason %in% c(tamsoat_nguyco_cao, tamsoat_nguyco_cao_bv, tamsoat_nguyco_cao_congdong) ~ "06. TAM SOAT NGUY CO CAO",
                                    test_reason %in% tamsoat_nguyco ~ "07. TAM SOAT NGUY CO",
                                    test_reason %in% tamsoat_vhh ~ "08. TAM SOAT VHH",
                                    test_reason %in% dieutra_dich ~ "09. DIEU TRA DICH",
                                    test_reason %in% c(kiemdich, kiemdich_trongnuoc, kiemdich_ngoainuoc) ~ "10. KIEM DICH",
                                    test_reason %in% c(giamsat_congdong) ~ "11. GIAM SAT CONG DONG",
                                    test_reason %in% c(giamsat_trongdiem) ~ "12. GIAM SAT TRONG DIEM",
                                    test_reason %in% giamsat_bv ~ "13. GIAM SAT BV",
                                    test_reason %in% theo_yeucau ~ "14. THEO YEU CAU",
                                    test_reason %in% xetnghiemlai ~ "15. XET NGHIEM LAI",
                                    test_reason %in% c(sau_cltt, theodoi_f0, theodoi_f0_csyt, theodoi_f0_nha, theodoi_f0_saudieutri, theodoi_khac) ~ "16. THEO DOI",
                                    test_reason %in% khac ~ "17. KHAC",
                                    TRUE ~ as.character(test_reason)
                                  ),
                                  
                                  test_type = case_when(
                                    is.na(ky_thuat_xn) ~ "MISSING",
                                    (ky_thuat_xn %in% c("11-08-2021", "14-08-2021")) | (grepl(pattern = "COUNTIF|PCR|U07T|VLOOKUP", x = ky_thuat_xn)) ~ "PCR",
                                    grepl(pattern = "TEST NHANH", x = ky_thuat_xn) ~ "TEST NHANH",
                                    grepl(pattern = "TEST MD", x = ky_thuat_xn) ~ "TEST MD",
                                    grepl(pattern = "NUÔI CẤY TẾ BÀO|PHÂN LẬP", x = ky_thuat_xn) ~ "PHAN LAP VIRUS",
                                    TRUE ~ "KHONG RO"
                                  )
                           )) %>%
  rename(loai_mau_xn = loai_mau,
         co_so_xet_nghiem = don_vi_xet_nghiem,
         thoi_gian_tra_ket_qua = thoi_gian_ket_qua)

saveRDS(xn_tong, file = file.path(data_path, "VAD", "xn_tong.rds"))
```

```{r}
xn_tong <- readRDS(file.path(data_path, "VAD", "xn_tong.rds"))
xn_chitiet <- readRDS(file.path(data_path, "VAD", "xn_chitiet.rds"))

xn <- rbindlist(list(xn_tong[, source := "tong"], 
                     xn_chitiet[, source := "chitiet"]), 
                fill = TRUE)

pcr1 <- xn[test_type == "PCR" & (loai_mau_xn == "MẪU ĐƠN" | (loai_mau_xn == "MẪU GỘP" & test_result == "AM TINH")) & !test_reason2 %in% c("16. THEO DOI"),
          .(n_pcr_nguoi = sum(so_nguoi),
            n_pos_nguoi = sum(test_result == "DUONG TINH")), 
          by = c("test_date_taken", "source")
]

pcr2 <- xn[test_type == "PCR" & !test_reason %in% c("16. THEO DOI"),
           .(n_pcr_test = length(unique(ma_xn)),
             n_pos_test = sum(test_result == "DUONG TINH")), 
           by = c("test_date_taken", "source")
]

pcr <- merge(pcr1, pcr2, by = c("test_date_taken", "source")) %>% rename(date = test_date_taken)
pcr_final <- rbind(
  pcr %>% 
    filter(source == "chitiet" & !date %in% ymd(c("2021-07-09", "2021-07-10", "2021-07-11", "2021-07-12", "2021-07-13", "2021-07-14", "2021-07-15"))),
  pcr %>% 
    filter(source == "tong" & date %in% ymd(c("2021-07-09", "2021-07-10", "2021-07-11", "2021-07-12", "2021-07-13", "2021-07-14", "2021-07-15")))
)

saveRDS(pcr, file = file.path(data_path, "VAD", "pcr.rds"))
saveRDS(pcr_final, file = file.path(data_path, "VAD", "pcr_final.rds"))
saveRDS(xn, file = file.path(data_path, "VAD", "xn.rds"))
```

```{r}
ggplot(data = pcr, aes(x = date, y = n_pcr_nguoi, group = source, color = source)) +
  geom_line() +
  theme_bw()

ggplot(data = subset(pcr, date >= ymd("2021-06-01") & date <= ymd("2021-08-01")), aes(x = date, y = n_pcr_nguoi, group = source, color = source)) +
  geom_line() +
  theme_bw()

ggplot(data = pcr, aes(x = date, y = n_pos_nguoi, group = source, color = source)) +
  geom_line() +
  theme_bw()

ggplot(data = subset(pcr, date >= ymd("2021-06-01") & date <= ymd("2021-08-01")), aes(x = date, y = n_pos_nguoi, group = source, color = source)) +
  geom_line() +
  theme_bw()
```

```{r}
tmp <- xn[test_type == "PCR" & (loai_mau_xn == "MẪU ĐƠN" | (loai_mau_xn == "MẪU GỘP" & test_result == "AM TINH")) & !test_reason2 %in% c("16. THEO DOI"),
          .(n_don = sum(so_nguoi[loai_mau_xn == "MẪU ĐƠN"]),
            n_gop = sum(so_nguoi[loai_mau_xn == "MẪU GỘP"]),
            n_don_duong = sum(so_nguoi[loai_mau_xn == "MẪU ĐƠN" & test_result == "DUONG TINH"]),
            n_don_am = sum(so_nguoi[loai_mau_xn == "MẪU ĐƠN" & test_result == "AM TINH"])), 
          by = c("test_date_taken", "source")
]

ggplot(data = subset(tmp, test_date_taken >= ymd("2021-07-01") & test_date_taken <= ymd("2021-07-30")), aes(x = test_date_taken, y = n_don, group = source, color = source)) +
  geom_line() +
  theme_bw()

ggplot(data = subset(tmp, test_date_taken >= ymd("2021-07-01") & test_date_taken <= ymd("2021-07-30")), aes(x = test_date_taken, y = n_gop, group = source, color = source)) +
  geom_line() +
  theme_bw()
```

#### Test nhanh

```{r}
testnhanh_newest <- subset(sum_current_file_latest, source == "testnhanh")
testnhanh <- NULL

for (i in c(1:nrow(testnhanh_newest))) {
  cat(i, "/", nrow(testnhanh_newest), "\n")
  xni <- janitor::clean_names(data.table(read_excel(path = testnhanh_newest$path[i], skip = 3, col_types = "text")))
  xni$file <- testnhanh_newest$name[i]
  testnhanh <- rbind(testnhanh, xni, fill = TRUE)
}
saveRDS(testnhanh, file = file.path(data_path, "VAD", "testnhanh_raw.rds"))
testnhanh <- readRDS(file.path(data_path, "VAD", "testnhanh_raw.rds"))

xn_testnhanh <- data.table(testnhanh %>%
                           mutate_all(.funs = toupper) %>%
                           rename(ho_va_ten = ho_ten,
                                  so_nha = so_nha_ten_duong,
                                  phuong_xa = phuong_xa_thi_tran,
                                  quan_huyen = quan_huyen_tp_tx,
                                  tinh_thanh = tinh_thanh_pho,
                                  ly_do_xn = ly_do,
                                  noi_lay_mau = noi_lay_mau_test_nhanh_loai_hinh,
                                  don_vi_lay_mau = co_so_thuc_hien,
                                  ket_qua = ket_qua_test_nhanh,
                                  thoi_gian_lay_mau = ngay_lay_mau_test_nhanh,
                                  thoi_gian_ghi_nhan = ngay_he_thong_ghi_nhan)  %>%
                           mutate(hcm = ifelse(is.na(tinh_thanh), 2,
                                               ifelse(tinh_thanh == "THÀNH PHỐ HỒ CHÍ MINH", 1, 0)),
                                  quanhuyen = case_when(
                                    hcm == 2 ~ "0. KHONG BIET",
                                    hcm == 0 ~ "0. NGOAI TPHCM",
                                    is.na(quan_huyen) ~ "0. KHONG BIET",
                                    quan_huyen %in% c("QUẬN 01", "QUẬN 1") ~ "QUẬN 01",
                                    quan_huyen %in% c("QUẬN 03", "QUẬN 3") ~ "QUẬN 03",
                                    quan_huyen %in% c("QUẬN 04", "QUẬN 4") ~ "QUẬN 04",
                                    quan_huyen %in% c("QUẬN 05", "QUẬN 5") ~ "QUẬN 05",
                                    quan_huyen %in% c("QUẬN 06", "QUẬN 6") ~ "QUẬN 06",
                                    quan_huyen %in% c("QUẬN 07", "QUẬN 7") ~ "QUẬN 07",
                                    quan_huyen %in% c("QUẬN 08", "QUẬN 8") ~ "QUẬN 08",
                                    quan_huyen %in% c("QUẬN 02", "QUẬN 2", "QUẬN 09", "QUẬN 9", "QUẬN THỦ ĐỨC", "THÀNH PHỐ THỦ ĐỨC") ~ "THÀNH PHỐ THỦ ĐỨC",
                                    quan_huyen %in% c("HUYỆN BÌNH CHÁNH", "HUYỆN CẦN GIỜ", "HUYỆN CỦ CHI", "HUYỆN HÓC MÔN", "HUYỆN NHÀ BÈ", "QUẬN BÌNH TÂN", "QUẬN BÌNH THẠNH", "QUẬN GÒ VẤP", "QUẬN PHÚ NHUẬN", "QUẬN TÂN BÌNH", "QUẬN TÂN PHÚ") ~ as.character(quan_huyen),
                                    TRUE ~ "0. KHONG BIET"
                                  ),
                                  namsinh = as.numeric(ifelse(is.na(nam_sinh), NA,
                                                   ifelse(grepl(pattern = "/", x = nam_sinh), substr(x = nam_sinh, start = 7, stop = 10), 
                                                          ifelse(as.numeric(nam_sinh) <= 1871 | as.numeric(nam_sinh) > 2021, NA, nam_sinh)))),
                                  tuoi = 2021 - namsinh,
                                  nhomtuoi = cut(tuoi, breaks = c(seq(0, 85, 5), 150), right = FALSE,
                                                 labels = c("0-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84", "85+")),
                                  nhomtuoi2 = ifelse(is.na(nhomtuoi), "MISSING", as.character(nhomtuoi)),
                                  gioi = gioi_tinh_nu_nam,
                                  tuoi_gioi = case_when(
                                    is.na(gioi) | is.na(tuoi) ~ NA_character_,
                                    gioi == "NAM" & tuoi <= 14 ~ "NAM 0-14",
                                    gioi == "NAM" & tuoi > 14 & tuoi <= 24 ~ "NAM 15-24",
                                    gioi == "NAM" & tuoi > 24 & tuoi <= 44 ~ "NAM 25-44",
                                    gioi == "NAM" & tuoi > 44 & tuoi <= 59 ~ "NAM 45-59",
                                    gioi == "NAM" & tuoi > 59 ~ "NAM 60+",
                                    gioi == "NỮ" & tuoi <= 14 ~ "NỮ 0-14",
                                    gioi == "NỮ" & tuoi > 14 & tuoi <= 24 ~ "NỮ 15-24",
                                    gioi == "NỮ" & tuoi > 24 & tuoi <= 44 ~ "NỮ 25-44",
                                    gioi == "NỮ" & tuoi > 44 & tuoi <= 59 ~ "NỮ 45-59",
                                    gioi == "NỮ" & tuoi > 59 ~ "NỮ 60+",
                                    TRUE ~ NA_character_
                                  ),
                                  test_datetime_taken = dmy_hm(paste(substr(x = thoi_gian_lay_mau, start = 7, stop = 16), substr(x = thoi_gian_lay_mau, start = 1, stop = 5)) , tz = "Asia/Ho_Chi_Minh"),
                                  test_date_taken = date(test_datetime_taken),
                                  test_datetime_result = dmy_hm(paste(substr(x = thoi_gian_ghi_nhan, start = 7, stop = 16), substr(x = thoi_gian_ghi_nhan, start = 1, stop = 5)), tz = "Asia/Ho_Chi_Minh"),
                                  test_date_result = date(test_datetime_result),
                                  test_result = case_when(
                                    is.na(ket_qua) ~ "CHUA XAC DINH",
                                    grepl(pattern = "DƯƠNG", x = ket_qua) ~ "DUONG TINH",
                                    grepl(pattern = "ÂM", x = ket_qua) ~ "AM TINH",
                                    grepl(pattern = "XÁC ĐỊNH", x = ket_qua) ~ "CHUA XAC DINH",
                                    grepl(pattern = "LẤY MẪU LẠI|MẪU KHÔNG ĐẠT|NGHI NGỜ", x = ket_qua) ~ "KHONG DAT",
                                    TRUE ~ "KHAC"
                                  ),
                            
                                  test_reason = toupper(stringi::stri_trans_general(str = ly_do_xn,  id = "Latin-ASCII")),
                                  test_reason2 = case_when(
                                    is.na(test_reason) ~ "MISSING",
                                    test_reason %in% maugop_duong ~ "01. MAU GOP DUONG",
                                    test_reason %in% testnhanh_duong ~ "02. TEST NHANH DUONG",
                                    test_reason %in% tamsoat_csyt ~ "03. TAM SOAT CSYT",
                                    test_reason %in% tamsoat_khambenh ~ "04. TAM SOAT KHAM BENH",
                                    test_reason %in% tamsoat_nguyco_ratcao ~ "05. TAM SOAT NGUY CO RAT CAO",
                                    test_reason %in% c(tamsoat_nguyco_cao, tamsoat_nguyco_cao_bv, tamsoat_nguyco_cao_congdong) ~ "06. TAM SOAT NGUY CO CAO",
                                    test_reason %in% tamsoat_nguyco ~ "07. TAM SOAT NGUY CO",
                                    test_reason %in% tamsoat_vhh ~ "08. TAM SOAT VHH",
                                    test_reason %in% dieutra_dich ~ "09. DIEU TRA DICH",
                                    test_reason %in% c(kiemdich, kiemdich_trongnuoc, kiemdich_ngoainuoc) ~ "10. KIEM DICH",
                                    test_reason %in% c(giamsat_congdong) ~ "11. GIAM SAT CONG DONG",
                                    test_reason %in% c(giamsat_trongdiem) ~ "12. GIAM SAT TRONG DIEM",
                                    test_reason %in% giamsat_bv ~ "13. GIAM SAT BV",
                                    test_reason %in% theo_yeucau ~ "14. THEO YEU CAU",
                                    test_reason %in% xetnghiemlai ~ "15. XET NGHIEM LAI",
                                    test_reason %in% c(sau_cltt, theodoi_f0, theodoi_f0_csyt, theodoi_f0_nha, theodoi_f0_saudieutri, theodoi_khac) ~ "16. THEO DOI",
                                    test_reason %in% khac ~ "17. KHAC",
                                    TRUE ~ as.character(test_reason)
                                  ),
                                  
                                  test_type = "TEST NHANH",
                                  
                                  test_place = toupper(stringi::stri_trans_general(str = noi_lay_mau,  id = "Latin-ASCII")),
                                  test_place2 = case_when(
                                    is.na(test_place) ~ NA_character_,
                                    test_place %in% c("PHIEN XET NGHIEM MAU") ~ NA_character_,
                                    grepl(pattern = "NOI DIEU TRI NGUOI BENH COVID|BENH VIEN DIEU TRI COVID|KHU CACH LY DIEU TRI F0", x = test_place) ~ "01. NƠI ĐIỀU TRỊ NGƯỜI BỆNH COVID",
                                    grepl(pattern = "CO SO Y TE KHONG DIEU TRI COVID", x = test_place) ~ "02. CƠ SỞ Y TẾ KHÔNG ĐIỀU TRỊ COVID",
                                    grepl(pattern = "KHU CACH LY", x = test_place) ~ "03. KHU CÁCH LY",
                                    grepl(pattern = "KHU PHONG TOA", x = test_place) ~ "04. KHU PHONG TỎA",
                                    grepl(pattern = "KCN, KCX, KHU CONG NGHE CAO, CSSX/KD|KCN, KCX, KHU CONG NGHE CAO, CSSX/KD|CO SO SAN XUAT", x = test_place) ~ "05. CƠ SỞ SẢN XUẤT",
                                    grepl(pattern = "CO QUAN HANH CHINH, CONG SO|CO QUAN HANH CHINH, CONG SO|TRU SO LAM VIEC", x = test_place) ~ "06. CÔNG SỞ",
                                    grepl(pattern = "CONG DONG", x = test_place) ~ "07. CỘNG ĐỒNG",
                                    grepl(pattern = "DON VI THUONG XUYEN LUU TRU DONG NGUOI|DON VI THUONG XUYEN LUU TRU DONG NGUOI", x = test_place) ~ "08. NƠI LƯU TRÚ ĐÔNG NGƯỜI", 
                                    grepl(pattern = "CHO, SIEU THI, CUA HANG TIEN LOI|CHO, SIEU THI, CUA HANG TIEN LOI", x = test_place) ~ "09. CHỢ, SIÊU THỊ",
                                    grepl(pattern = "SAN BAY, BEN XE, BEN TAU, GA DUONG SAT|SAN BAY, BEN XE, BEN TAU, GA DUONG SAT", x = test_place) ~ "10. SÂN BAY, BẾN XE, GA",
                                    grepl(pattern = "TRUONG HOC", x = test_place) ~ "11. TRƯỜNG HỌC", 
                                    grepl(pattern = "TAI NHA", x = test_place) ~ "12. TẠI NHÀ",
                                    grepl(pattern = "VUNG XANH", x = test_place) ~ "13. VÙNG XANH",
                                    grepl(pattern = "VUNG CAN XANH", x = test_place) ~ "14. VÙNG CẬN XANH",
                                    grepl(pattern = "VUNG VANG", x = test_place) ~ "15. VÙNG VÀNG",
                                    grepl(pattern = "VUNG CAM", x = test_place) ~ "16. VÙNG CAM",
                                    grepl(pattern = "VUNG DO", x = test_place) ~ "17. VÙNG ĐỎ", 
                                    TRUE ~ "18. KHAC"
                                  )
                           ))
saveRDS(xn_testnhanh, file = file.path(data_path, "VAD", "xn_testnhanh.rds"))
```


```{r}
getAllMondays <- function(year) {
  ## source: https://stackoverflow.com/questions/9166437/get-dates-of-a-certain-weekday-from-a-year-in-r
    days <- as.POSIXlt(paste(year, 1:366, sep="-"), format="%Y-%j")
    Ms <- days[days$wday==1]
    Ms[!is.na(Ms)]  # Needed to remove NA from day 366 in non-leap years
}



epiweek_date <- rbind(
  data.frame(epiweek = 1:53,
             year = 2020,
             date_first = ymd(getAllMondays(2020)))
)
```


```{r}
cases <- readRDS(file = file.path(ncsc_data_path, "clean", "covid.rds")) %>%
  ## epidemiological week
  mutate(epiweek = isoweek(date),
         year = year(date))

death <- cases %>%
  filter(var == "cum_deaths") %>%
  group_by(province) %>%
  arrange(date) %>%
  mutate(deaths = c(0, diff(n))) %>%
  ungroup() %>%
  mutate(var = "deaths",
         n = deaths) %>%
  select(-deaths)

death2 <- death %>%
  mutate(var = "deaths 2",
         n = pmax(n, 0))
  
cases <- rbind(cases, death, death2) %>%
  arrange(date, province)

cases_week <- cases %>%
  group_by(province, var, year, epiweek) %>%
  summarise(n = sum(n),
            .groups = "drop") %>%
  ungroup()
```

### prevalence

```{r}
ggplot(data = filter(cases, var == "prevalence"), aes(x = date, y = n)) +
  geom_line() +
  geom_vline(xintercept = today, color = "red") +
  facet_wrap(~ province, scales = "free_y") +
  theme_bw()
```

### incidence

```{r}
ggplot(data = filter(cases, var == "incidence"), aes(x = date, y = n)) +
  geom_line() +
  geom_vline(xintercept = today, color = "red") +
  facet_wrap(~ province, scales = "free_y") +
  theme_bw()
```
```{r}
ggplot(data = filter(cases, var == "cum_incidence"), aes(x = date, y = n)) +
  geom_line() +
  geom_vline(xintercept = today, color = "red") +
  facet_wrap(~ province, scales = "free_y") +
  theme_bw()
```

### cum_deaths

```{r}
ggplot(data = filter(cases, var == "cum_deaths"), aes(x = date, y = n)) +
  geom_line() +
  geom_vline(xintercept = today, color = "red") +
  facet_wrap(~ province, scales = "free_y") +
  theme_bw()
```

```{r}
ggplot(data = filter(cases, var == "deaths"), aes(x = date, y = n)) +
  geom_line() +
  geom_vline(xintercept = today, color = "red") +
  facet_wrap(~ province, scales = "free_y") +
  theme_bw()
```

```{r}
ggplot(data = filter(cases, var == "deaths 2"), aes(x = date, y = n)) +
  geom_line() +
  geom_vline(xintercept = today, color = "red") +
  facet_wrap(~ province, scales = "free_y") +
  theme_bw()
```

## vaccines

```{r}
vaccines <- readRDS(file = file.path(ncsc_data_path, "clean", "vaccines.rds"))
```
