---
title: "Thuoc"
output: html_notebook
---

## for report

```{r}
library(tidyverse)
library(lubridate)
library(writexl)
library(readxl)

data_path <- file.path(Lmisc::get.dropbox.folder(), "Workspace", "Database", "COVID19", "DOH", "nvduoc", "data")
today <- ymd("2022-02-08")
today2 <- gsub(pattern = "-", x = today, replacement = "")

## TTYT
ttyt <- read.csv(file = file.path(data_path, today2, "BÁO CÁO SỞ Y TẾ HÀNG NGÀY 03 TÚI THUỐC F0 - v2.0.csv"))
names(ttyt) <- c("datetime", "email", "date_report", "reporter", "phone", "place",
                 "A_TTYT_out_cum", "A_TTYT_rem_cum", "A_TTYT_out_inc", "A_TYT_out_cum", "A_TYT_rem_cum", "A_TYT_out_inc",
                 "B_TTYT_out_cum", "B_TTYT_rem_cum", "B_TTYT_out_inc", "B_TYT_out_cum", "B_TYT_rem_cum", "B_TYT_out_inc",
                 "C_TTYT_out_cum", "C_TTYT_rem_cum", "C_TTYT_out_inc", "C_TYT_out_cum", "C_TYT_rem_cum", "C_TYT_out_inc", "C_get_cum", "C_get_inc",
                 "K_TTYT_out_cum", "K_TTYT_rem_cum", "K_TTYT_out_inc", "K_TYT_out_cum", "K_TYT_rem_cum", "K_TYT_out_inc")

key_ttyt <- c("Quận 1", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận 10", "Quận 11", "Quận 12", 
              "Quận Bình Tân", "Huyện Bình Chánh", "Quận Bình Thạnh", "Huyện Nhà Bè", "Huyện Hóc Môn", "Huyện Cần Giờ", 
              "Huyện Củ Chi", "Quận Tân Bình", "Quận Tân Phú", "Quận Phú Nhuận", "Quận Gò Vấp", "Thành Phố Thủ Đức")

ttyt2 <- ttyt %>%
  mutate(ngaygio = ymd_hms(sapply(datetime, FUN = function(x){paste(strsplit(x, split = " ")[[1]][1:2], collapse = " ")})),
         pm = sapply(datetime, FUN = function(x){strsplit(x, split = " ")[[1]][3]}),
         ngay = ymd(sapply(datetime, FUN = function(x){strsplit(x, split = " ")[[1]][1]})),
         ngaygio2 = ymd_hms(ifelse(pm == "PM", as.character(ngaygio + hours(12)), as.character(ngaygio + hours(0)))),
         place = factor(ifelse(place %in% c("Tân Phú", "Quận Tân Phú"), "Quận Tân Phú",
                               ifelse(place %in% c("Hóc Môn", "Huyện Hóc Môn"), "Huyện Hóc Môn",
                                      ifelse(place %in% c("Củ Chi", "Huyện Củ Chi"), "Huyện Củ Chi",
                                             ifelse(place %in% c("Nhà Bè", "Huyện Nhà Bè"), "Huyện Nhà Bè",
                                                    ifelse(place %in% c("Cần Giờ", "Huyện Cần Giờ"), "Huyện Cần Giờ",
                                                           ifelse(place %in% c("Bình Thạnh", "Quận Bình Thạnh"), "Quận Bình Thạnh",
                                                                  ifelse(place %in% c("Phú Nhuận", "Quận Phú Nhuận"), "Quận Phú Nhuận",
                                                                         ifelse(place %in% c("Gò Vấp", "Quận Gò Vấp"), "Quận Gò Vấp",
                                                                                ifelse(place %in% c("Thủ Đức", "Thành Phố Thủ Đức"), "Thành Phố Thủ Đức",
                                                                                       ifelse(place %in% c("Bình Tân", "Quận Bình Tân"), "Quận Bình Tân",
                                                                                              ifelse(place %in% c("Tân Bình", "Quận Tân Bình"), "Quận Tân Bình",
                                                                                                     ifelse(place %in% c("Bình Chánh", "Huyện Bình Chánh"), "Huyện Bình Chánh", place)))))))))))),
                        levels = key_ttyt)) %>%
  group_by(place, ngay) %>%
  arrange(desc(ngaygio2)) %>%
  slice(1) %>%
  ungroup()

ttyt_bc <- merge(
  data.frame(place = factor(key_ttyt, levels = key_ttyt)),
  ttyt2 %>%
  select(ngay, ngaygio2, place, email, reporter,
         A_TTYT_out_cum, A_TTYT_rem_cum, A_TYT_out_inc, A_TYT_out_cum,
         B_TTYT_out_cum, B_TTYT_rem_cum, B_TYT_out_inc, B_TYT_out_cum,
         C_TTYT_out_cum, C_TTYT_rem_cum, C_TYT_out_inc, C_TYT_out_cum,
         K_TTYT_out_cum, K_TTYT_rem_cum, K_TYT_out_inc, K_TYT_out_cum) %>%
  filter(ngay == today),
  by = "place", all.x = TRUE) %>%
  arrange(place)

write_xlsx(x = ttyt_bc, path = file.path(data_path, "tmp", "ttyt_bc.xlsx"))  

## BV da chien
bvdc <- read.csv(file = file.path(data_path, today2, "BÁO CÁO SỞ Y TẾ HÀNG NGÀY 03 TÚI THUỐC F0 - BV Da chien.csv"))
names(bvdc) <- c("datetime", "email", "date_report", "reporter", "phone", "place",
                 "out_cum", "out_inc", "rem_cum", "get_cum", "get_inc")
bvdc$place[bvdc$datetime == "2021/12/24 6:21:53 PM GMT+7" & bvdc$place == "Bệnh viện Dã chiến Điều trị Covid-19 Thủ Đức số 2 (KTX Cao đẳng công thương)" & bvdc$email == "dsnguyenthithuha@gmail.com"] <- "Bệnh viện Dã chiến Điều trị Covid-19 Thủ Đức số 3 (Chung cư C8)"

key_bvdc <- c("BV Dã chiến thu dung ĐT COVID-19 số 1", "BV Dã chiến thu dung ĐT COVID-19 số 2", 
              "BV Dã chiến thu dung ĐT COVID-19 số 3", "BV Dã chiến thu dung ĐT COVID-19 số 4", 
              "BV Dã chiến thu dung ĐT COVID-19 số 5", "BV Dã chiến thu dung ĐT COVID-19 số 6", 
              "BV Dã chiến thu dung ĐT COVID-19 số 7", "BV Dã chiến thu dung ĐT COVID-19 số 8", 
              "BV Dã chiến thu dung ĐT COVID-19 số 9", "BV Dã chiến thu dung ĐT COVID-19 số 10",
              "BV Dã chiến thu dung ĐT COVID-19 số 11", "BV Dã chiến thu dung ĐT COVID-19 số 12", 
              "BV Dã chiến thu dung ĐT COVID-19 số 13", "Bệnh viện dã chiến điều trị COVID-19 Bình Thạnh số 1 (số 01 Chu Văn An)", 
              "BV Dã chiến thu dung ĐT COVID-19 số 16", "BV Dã chiến số 5A/QK7 (QK 317)",
              "BV Dã chiến Củ Chi", "Bệnh viện Dã chiến thu dung điều trị COVID-19 Số 14", 
              "Bệnh viện Dã chiến điều trị COVID - 19 Củ Chi số 01 (Liên minh công nông)", "Bệnh viện Dã chiến Điều trị Covid Thủ Đức số 1 (Chung cư Bình Minh) ",
              "Bệnh viện Dã chiến điều trị COVID-19 đa tầng Tân Bình", "Bệnh viện Dã chiến điều trị Covid-19 Huyện Bình Chánh" , 
              "Bệnh viện Dã chiến Điều trị COVID-19 Phú Nhuận số 1 (05 Hoàng Minh Giám)", "Bệnh viện Dã chiến Điều trị COVID-19 Phú Nhuận số 2 (128 Nguyễn Trọng Tuyển)",
              "Bệnh viện Dã chiến Điều trị COVID-19 Quận 1", "Bệnh viện Dã chiến Điều trị Covid-19 Quận 7 số 1", 
              "Bệnh viện Dã chiến Điều trị COVID-19 Quận 8 số 1 (địa chỉ số 6 Dương Quang Đông P5 quận 8)", "Bệnh viện Dã chiến Điều trị Covid-19 Thủ Đức số 2 (KTX Cao đẳng công thương)", 
              "Bệnh viện Dã chiến Điều trị Covid-19 Thủ Đức số 3 (Chung cư C8)", "Bệnh viện thu dung, điều trị COVID-19 Quận 11", 
              "Bệnh viện dã chiến điều trị COVID-19 Quận 1 số 1", "Bệnh viện dã chiến 3 tầng số 16", 
              "Bệnh viện dã chiến truyền nhiễm số 5C thuộc Cục hậu cần- Quân khu 7", "Bệnh viện thu dung điều trị COVID-19 Quận 5 (trực thuộc UBND Quận 5)",
              "Bệnh viện điều trị COVID-19 Phú Nhuận-Viện Y dược học dân tộc Thành phố")

bvdc2 <- bvdc %>%
  mutate(ngaygio = ymd_hms(sapply(datetime, FUN = function(x){paste(strsplit(x, split = " ")[[1]][1:2], collapse = " ")})),
         pm = sapply(datetime, FUN = function(x){strsplit(x, split = " ")[[1]][3]}),
         ngay = ymd(sapply(datetime, FUN = function(x){strsplit(x, split = " ")[[1]][1]})),
         ngaygio2 = ymd_hms(ifelse(pm == "PM", as.character(ngaygio + hours(12)), as.character(ngaygio + hours(0)))),
         place = factor(place, levels = key_bvdc)) %>%
  group_by(place, ngay) %>%
  arrange(desc(ngaygio2)) %>%
  slice(1) %>%
  ungroup()

bvdc_bc <- merge(
  data.frame(place = factor(key_bvdc, levels = key_bvdc)),
  bvdc2 %>%
  select(ngay, ngaygio2, place, email, reporter, out_inc, out_cum) %>%
  filter(ngay == today),
  by = "place", all.x = TRUE) %>%
  arrange(place)

write_xlsx(x = bvdc_bc, path = file.path(data_path, "tmp", "bvdc_bc.xlsx"))  

## BV dieu tri
bvdt <- read.csv(file = file.path(data_path, today2, "Bệnh viện Khác - BÁO CÁO SỞ Y TẾ HÀNG NGÀY TÚI THUỐC C.csv"))
names(bvdt) <- c("datetime", "email", "date_report", "reporter", "phone", "place",
                 "out_cum", "out_inc", "rem_cum", "get_cum", "get_inc")

key_bvdt <- c("Bệnh viện 175", "Bệnh viện 30/4", "Bệnh viện An Bình", "Bệnh viện Bình Dân", "Bệnh viện Điều trị Covid 19 Sài Gòn", 
              "Bệnh viện Điều trị COVID-19 Cần Giờ", "Bệnh viện ĐKKV Thủ Đức", "Bệnh viện FV", "Bệnh viện Gia An 115", "Bệnh viện Hùng Vương", 
              "Bệnh viện Huyện Củ Chi", "Bệnh viện Lê Văn Thịnh", "Bệnh viện Mắt", "Bệnh viện Nguyễn Tri Phương", "Bệnh viện Nhân dân 115",
              "Bệnh viện Nhi Đồng Thành phố", "Bệnh viện quận 4", "Bệnh viện Quân dân y Miền Đông", "Bệnh viện Quận Gò Vấp", "Bệnh viện Quận Phú Nhuận", 
              "Bệnh viện Quận Tân Phú", "Bệnh viện Tâm Thần", "Bệnh viện Tân Hưng", "Bệnh viện Tim Tâm Đức", "Bệnh viện Triều An", 
              "Bệnh viện Trung ương Huế - Trung tâm Hồi sức tích cực COVID-19", "Bệnh viện Trưng Vương", "Bệnh viện Vạn Hạnh", "Bệnh viện Công an Thành phố Hồ Chí Minh", "Bệnh viện Thành phố Thủ Đức",
              "Viện Tim", "Bệnh viện Nhân dân Gia Định", "Bệnh viện Nguyễn Trãi", "Bệnh viện ĐKKV Hóc Môn", "Bệnh viện quận 8",
              "Bệnh viện Lê Văn Việt", "Bệnh viện Tai Mũi Họng", "Ban Bảo vệ sức khỏe TW", "Bệnh viện Đa khoa Hoàn Mỹ Sài Gòn", "Bệnh viện điều trị Covid-19 Hoàn Mỹ Thủ Đức",
              "Bệnh viên Đa khoa Quốc tế Nam Sài Gòn", "Bệnh viện Đa khoa Hồng Đức III", "Bệnh viện Quận 1", "Bệnh viện Quận 11", "Bệnh viện Quận 12", 
              "Bệnh viện điều trị Covid -19 Bình Chánh", "Bệnh viện Quận Bình Thạnh" , "Bệnh viện Nhân Ái", "Bệnh viện Nhà Bè", "Bệnh viện Đa khoa Tâm Trí Sài Gòn",
              "Bệnh viện PHCN & ĐTBNN", "Bệnh viện Nhi Đồng 1", "Bệnh viện Quân y 7A", "Bệnh viện Nhi Đồng 2",
              "Bệnh viện Bệnh Nhiệt đới", "Bệnh viện Quận 6", "Bệnh viện Quận 7", "Bệnh viện Xuyên Á", "Bệnh viện Răng hàm mặt Trung Ương", "Bệnh viện đa khoa khu vực Củ Chi", "Bệnh viện Quốc Ánh", "Bệnh viện An Sinh")

bvdt2 <- bvdt %>%
  mutate(ngaygio = ymd_hms(sapply(datetime, FUN = function(x){paste(strsplit(x, split = " ")[[1]][1:2], collapse = " ")})),
         pm = sapply(datetime, FUN = function(x){strsplit(x, split = " ")[[1]][3]}),
         ngay = ymd(sapply(datetime, FUN = function(x){strsplit(x, split = " ")[[1]][1]})),
         ngaygio2 = ymd_hms(ifelse(pm == "PM", as.character(ngaygio + hours(12)), as.character(ngaygio + hours(0)))),
         place = factor(place, levels = key_bvdt)) %>%
  group_by(place, ngay) %>%
  arrange(desc(ngaygio2)) %>%
  slice(1) %>%
  ungroup()

bvdt_bc <- merge(
  data.frame(place = factor(key_bvdt, levels = key_bvdt)),
  bvdt2 %>%
  select(ngay, ngaygio2, place, email, reporter, out_inc, out_cum) %>%
  filter(ngay == today),
  by = "place", all.x = TRUE) %>%
  arrange(place)

write_xlsx(x = bvdt_bc, path = file.path(data_path, "tmp", "bvdt_bc.xlsx"))  
```

## descriptive analysis

```{r}
library(ggplot2)
plotdat <- ttyt2 %>%
  mutate(C_TYT_out_inc = as.numeric(C_TYT_out_inc),
         C_TTYT_out_inc = as.numeric(C_TTYT_out_inc),
         C_TTYT_out_cum = as.numeric(C_TTYT_out_cum),
         C_TYT_out_cum = as.numeric(C_TYT_out_cum),
         C_out_cum = C_TYT_out_cum/C_TTYT_out_cum,
         C_out_inc = C_TYT_out_inc/C_TTYT_out_inc)
```

```{r}
ggplot(data = plotdat, aes(x = ngay, y = C_TYT_out_inc)) +
  geom_line(aes(group = 1)) +
  geom_point() +
  facet_wrap(~ place) +
  theme_bw()
```

```{r}
ggplot(data = plotdat, aes(x = ngay)) +
  geom_line(aes(group = 1, y = C_TTYT_out_cum)) +
  geom_line(aes(group = 1, y = C_TYT_out_cum), col = "red") +
  geom_point(aes(y = C_TTYT_out_cum), size = 1) +
  geom_point(aes(y = C_TYT_out_cum), col = "red", size = 1) +
  facet_wrap(~ place, scale = "free_y") +
  theme_bw()
```
```{r}
ggplot(data = plotdat, aes(x = ngay)) +
  geom_line(aes(group = 1, y = C_TTYT_out_inc)) +
  geom_line(aes(group = 1, y = C_TYT_out_inc), col = "red") +
  geom_point(aes(y = C_TTYT_out_inc), size = 1) +
  geom_point(aes(y = C_TYT_out_inc), col = "red", size = 1) +
  facet_wrap(~ place, scale = "free_y") +
  theme_bw()
```


```{r}
ggplot(data = plotdat, aes(x = ngay, y = C_out_cum)) +
  geom_hline(yintercept = 1, col = "red") +
  geom_hline(yintercept = 0.8, col = "red", linetype = 2) +
  geom_line(aes(group = 1)) +
  geom_point(size = 1) +
  scale_y_continuous(name = "Tổng xuất TYT/Tổng xuất TTYT [Túi C]", limits = c(0, 1.5)) +
  scale_x_date(name = "Ngày", breaks = "7 days") +
  facet_wrap(~ place) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))
#ggsave(filename = file.path(data_path, "..", "baocao", "figures", "C_out_cum.png"), width = 12, height = 10)
ggsave(filename = file.path(data_path, "..", "baocao", "figures", "C_out_cum_20211228.png"), width = 12, height = 10)
```
* Đánh giá nhu cầu và thu hồi

```{r}
## data on # of pack DOH deliver
file_tmp <- list.files(file.path(data_path, "..", "baocao", today2), full.names = TRUE)
file_ttyt <- file_tmp[grepl(pattern = "TTYT", x = file_tmp)]
sheets <- excel_sheets(file_ttyt)
tmp <- read_excel(path = file_ttyt, sheet = " TTYT 09-01 ", skip = 2)[1:22, c(2, 16)] %>% set_names(nm = c("quan", "doh"))
tmp2 <- data.frame(place = key_ttyt, tmp)

plotdat2 <- merge(plotdat, tmp2[, c(1, 3)], by = "place", all.x = TRUE)

ggplot(data = plotdat2, aes(x = ngay)) +
  geom_hline(aes(yintercept = doh), col = "red") +
  geom_line(aes(group = 1, y = C_TTYT_out_cum)) +
  geom_line(aes(group = 1, y = C_TYT_out_cum), col = "red") +
  geom_point(aes(y = C_TTYT_out_cum), size = 1) +
  geom_point(aes(y = C_TYT_out_cum), col = "red", size = 1) +
  facet_wrap(~ place, scale = "free_y") +
  theme_bw()
```

```{r}
dat <- read_excel(path = file.path(Lmisc::get.dropbox.folder(), "Workspace", "Research", "DOH_COVID19", "dulieu", "database", "doh_bcn_bvdt_tang01.xlsx")) %>%
  mutate(n_moi = as.numeric(n_f0tainha_moi_24h) + as.numeric(n_f0moi_chuyencachly_24h),
         ngaybc = ymd(ngaybc))

ggplot(data = subset(dat, !is.na(n_moi)), aes(x = ngaybc, y = n_moi)) +
  geom_line(aes(group = 1)) +
  facet_wrap(~ quan, scale = "free_y") +
  scale_x_date(breaks = "1 month") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))

dat2 <- dat %>%
  filter(ngaybc >= (ymd("2022-01-09") - 14)) %>%
  select(quan, ngaybc, n_moi) %>%
  mutate(n_moi = ifelse(n_moi < 0, 0, n_moi))

ggplot(data = dat2, aes(x = ngaybc, y = n_moi)) +
  geom_line(aes(group = 1)) +
  facet_wrap(~ quan, scale = "free_y") +
  #scale_x_date(breaks = "1 month") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))

dat3 <- dat2 %>%
  group_by(quan)

res <- do(dat3, 
   augment(x = lm(n_moi ~ ngaybc, data = .), newdata = data.frame(ngaybc = ymd("2022-01-09") + c(1:30)))) %>%
  mutate(n_moi = pmax(.fitted, 0))
  
ggplot(data = res, aes(x = ngaybc, y = n_moi)) +
  geom_line(aes(group = 1)) +
  facet_wrap(~ quan, scale = "free_y") +
  #scale_x_date(breaks = "1 month") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90))

res2 <- res %>%
  group_by(quan) %>%
  summarise(n = round(sum(n_moi)))
```


## Ghi chú

### Ngày 24/12/2021

* Quận 8, Tổng xuất túi thuốc C của TTYT ngày 24/12/2021 = 27533 (sai? số đúng là 2753???)
* Các quận có tốc độ phát túi C cho F0 tại TYT chậm (lượng phát của TYT < 80% lượng phát của TTYT): Bình Tân, Tân Phú, TP Thủ Đức
